source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "rubyzip", "~> 2.3.0"

# Jekyll themes
gem "jekyll-theme-minimal"
gem "jekyll-theme-cayman"
gem "jekyll-theme-slate"
gem "jekyll-theme-architect"
gem "jekyll-theme-modernist"
